# Generated by Django 3.2.19 on 2026-02-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Identifiant unique du nœud (ex: 'start', 'facturation', 'video_facture')", max_length=100, unique=True, verbose_name='Code unique')),
                ('type', models.CharField(choices=[('message', 'Message simple'), ('video', 'Message avec vidéo')], default='message', max_length=20, verbose_name='Type de nœud')),
                ('content', models.TextField(help_text="Le message affiché à l'utilisateur", verbose_name='Contenu du message')),
                ('video_index', models.IntegerField(blank=True, help_text='Index de la vidéo dans la playlist YouTube (de 0 à 12)', null=True, verbose_name='Index de la vidéo')),
                ('ordre', models.IntegerField(default=0, help_text="Pour trier les nœuds dans l'admin", verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Nœud chatbot',
                'verbose_name_plural': 'Nœuds chatbot',
                'db_table': 'aide_chatbot_node',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Texte affiché sur le bouton', max_length=200, verbose_name='Libellé du bouton')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('next_node', models.ForeignKey(help_text='Nœud à afficher quand on clique sur ce bouton', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_options', to='aide.chatbotnode', verbose_name='Nœud suivant')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='aide.chatbotnode', verbose_name='Nœud parent')),
            ],
            options={
                'verbose_name': 'Option chatbot',
                'verbose_name_plural': 'Options chatbot',
                'db_table': 'aide_chatbot_option',
                'ordering': ['ordre', 'label'],
            },
        ),
    ]
