# Generated by Django 3.2.23 on 2025-11-13 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0206_auto_20251113_1256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.structure",
                verbose_name="Structure",
            ),
        ),
    ]
