# Generated by Django 3.2.19 on 2025-11-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0208_merge_20251118_0937"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="besoin_certification",
            field=models.BooleanField(
                default=False, verbose_name="Besoin de certification"
            ),
        ),
    ]
