# Generated by Django 3.2.23 on 2025-12-10 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0210_comptebancaire_bilan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptebancaire',
            name='bilan',
        ),
        migrations.AddField(
            model_name='comptacategorie',
            name='bilan',
            field=models.BooleanField(default=True, verbose_name='Compte intégré au bilan'),
        ),
        migrations.AddField(
            model_name='comptaoperation',
            name='remb_avance',
            field=models.BooleanField(default=False, verbose_name='Avance régularisée'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='structures_admin',
            field=models.ManyToManyField(blank=True, related_name='utilisateur_structures_admin', to='core.Structure', verbose_name='Structures admin'),
        ),
        migrations.CreateModel(
            name='CompteBancaireAvance',
            fields=[
                ('idcompteavance', models.AutoField(db_column='IDcompte', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure')),
            ],
            options={
                'verbose_name': "compte d'avance",
                'verbose_name_plural': "comptes d'avances",
                'db_table': 'comptes_bancaires_avance',
            },
        ),
        migrations.CreateModel(
            name='ComptaAvance',
            fields=[
                ('idcompta_avance', models.AutoField(db_column='IDcompta_avance', primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom complet ')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure ')),
            ],
            options={
                'verbose_name': 'avance',
                'verbose_name_plural': 'avances',
                'db_table': 'compta_avance',
            },
        ),
        migrations.AddField(
            model_name='comptaoperation',
            name='avance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.comptaavance', verbose_name='Avance'),
        ),
    ]
