# Generated by Django 3.2.23 on 2025-12-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0212_rectif'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptaoperation',
            name='regul_avance',
            field=models.BooleanField(default=False, verbose_name="Opération de régularisation d'avance"),
        ),
    ]
