# Generated by Django 3.2.23 on 2025-12-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0213_comptaoperation_regul_avance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptaoperation',
            name='remb_avance',
            field=models.IntegerField(blank=True, help_text='Identifiant utilisé pour relier les opérations entre elles (ex: ID de régularisation)', null=True, verbose_name='Référence de régularisation'),
        ),
    ]
