# Generated by Django 3.2.23 on 2025-12-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0214_alter_comptaoperation_remb_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='pay_org_tpe',
            field=models.CharField(choices=[('HELLOASSO', 'HelloAsso'), ('STRIPE', 'Stripe'), ('PAYASSO', 'PayAsso'), ('AUTRE', 'Divers')], default='HELLOASSO', max_length=100, verbose_name='Passerelle de paiement'),
        ),
    ]
