# Generated by Django 3.2.23 on 2025-12-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0215_activite_pay_org_tpe'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelloAssoConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Client ID HelloAsso', max_length=255)),
                ('client_secret', models.CharField(help_text='Client Secret HelloAsso', max_length=255)),
                ('org_slug', models.CharField(help_text='Organisation slug HelloAsso', max_length=255)),
                ('actif', models.BooleanField(default=True, help_text='Activer cette configuration')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('activites', models.ManyToManyField(blank=True, related_name='helloasso_configs', to='core.Activite')),
            ],
            options={
                'verbose_name': 'Configuration HelloAsso',
                'verbose_name_plural': 'Configurations HelloAsso',
            },
        ),
    ]
