# Generated by Django 3.2.23 on 2025-12-28 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0216_helloassoconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementTpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('SUCCES', 'Succès'), ('ECHEC', 'Échec')], max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('helloasso_checkout_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prestation')),
            ],
        ),
    ]
