# Generated by Django 3.2.23 on 2025-12-28 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0217_paiementtpe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenHA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_intent_id', models.CharField(max_length=100, unique=True)),
                ('organisation_slug', models.CharField(max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_helloasso', to='core.prestation')),
            ],
        ),
    ]
