# Generated by Django 3.2.23 on 2025-12-31 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_auto_20251119_2047'),
        ('core', '0219_auto_20251230_1031'),
    ]

    operations = [
    ]
