# Generated by Django 3.2.23 on 2026-01-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0221_auto_20260108_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Structure archivée'),
        ),
    ]
