# Generated by Django 3.2.23 on 2026-01-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0222_structure_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Activité active'),
        ),
        migrations.AlterField(
            model_name='comptaoperation',
            name='remb_avance',
            field=models.IntegerField(blank=True, default=0, help_text='Identifiant utilisé pour relier les opérations entre elles (ex: ID de régularisation)', null=True, verbose_name='Référence de régularisation'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Structure active'),
        ),
    ]
