# Generated by Django 3.2.23 on 2026-01-13 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0223_auto_20260112_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='typededuction',
            name='remb',
            field=models.BooleanField(default=True, verbose_name='Déduction payée par un tier'),
        ),
        migrations.AddField(
            model_name='typededuction',
            name='structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure associée'),
            preserve_default=False,
        ),
    ]
