# Generated by Django 3.2.23 on 2026-01-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0224_auto_20260113_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='remb',
            field=models.BooleanField(default=False, verbose_name='Déduction remboursée'),
        ),
    ]
