# Generated by Django 3.2.23 on 2026-01-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0225_deduction_remb'),
    ]

    operations = [
        migrations.AddField(
            model_name='modereglement',
            name='encaissement',
            field=models.BooleanField(default=False, help_text="(n'est pas inclus dans la compta automatiquement)", verbose_name="Encaissé par l'organisateur"),
        ),
    ]
