# Generated by Django 3.2.23 on 2026-01-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0226_modereglement_encaissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptacategorie',
            name='orga',
            field=models.BooleanField(default=False, verbose_name="Compte lié à l'organisateur (part orga., cotisations,...)"),
        ),
    ]
