# Generated by Django 3.2.23 on 2026-01-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0229_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptaoperation',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='comptaventilation',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
    ]
