# Generated by Django 3.2.23 on 2026-02-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0232_alter_utilisateur_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCompte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du compte Stripe (ex: Section Judo)', max_length=100)),
                ('secret_key', models.CharField(max_length=255)),
                ('publishable_key', models.CharField(max_length=255)),
                ('webhook_secret', models.CharField(blank=True, help_text='Clé whsec_... pour automatiser la validation des factures', max_length=255, null=True)),
                ('actif', models.BooleanField(default=True, help_text='Activer cette configuration')),
                ('activites', models.ManyToManyField(related_name='stripe_comptes', to='core.Activite')),
            ],
            options={
                'verbose_name': 'Configuration Stripe',
                'verbose_name_plural': 'Configurations Stripe',
            },
        ),
    ]
